=== u-u-h/adpc/interfacer/interface.dtd
<!DOCTYPE interface [
<!ELEMENT interface ( versioninfo, messages, manual?, module*, option* ) >
   <!ATTLIST interface name        CDATA          #REQUIRED
                       version     CDATA          #REQUIRED
                       author      CDATA          #REQUIRED
                       design      (mono | color) #REQUIRED
                       lib         (std  | rna)   #REQUIRED
                       interactive (on | off)     #REQUIRED>

<!ELEMENT versioninfo (#PCDATA) >

<!ELEMENT messages (interactive_welcome, interactive_commandline, interactive_help_header) >
   <!ELEMENT interactive_welcome     (#PCDATA) >
   <!ELEMENT interactive_commandline (#PCDATA) >
   <!ELEMENT interactive_help_header (#PCDATA) >

 <!ELEMENT manual (synopsis?, introduction?, examples?)>
   <!ELEMENT synopsis                (#PCDATA) >
   <!ELEMENT introduction            (#PCDATA) >
   <!ELEMENT examples                (#PCDATA) >

<!ELEMENT module EMPTY >
   <!ATTLIST module   name                  CDATA #REQUIRED
                      source                CDATA #REQUIRED
                      adpc                  CDATA #REQUIRED
                      condition             CDATA #REQUIRED 
                      output_optimal        CDATA #REQUIRED  
                      output_subopt_start   CDATA #REQUIRED
                      output_subopt         CDATA #REQUIRED
                      output_subopt_end     CDATA #REQUIRED
                      main_name             CDATA #REQUIRED>

<!ELEMENT option ( (help | longhelp | version | 
                    switch | set | switchset | file | direct |
                    comment ), 
                   code?, man? ) >
    <!ATTLIST option switch CDATA #REQUIRED 
                     argtext CDATA #IMPLIED 
                     text   CDATA #REQUIRED >

<!ELEMENT code (#PCDATA) >
<!ELEMENT man (#PCDATA) >

<!ELEMENT help EMPTY >
<!ELEMENT longhelp EMPTY >

<!ELEMENT version EMPTY >

<!ELEMENT switch EMPTY >
    <!ATTLIST switch var CDATA #REQUIRED 
                     settext CDATA #REQUIRED
                     infotext CDATA #REQUIRED 
                     default  (on|off) #REQUIRED >

<!ELEMENT set EMPTY >
    <!ATTLIST set var CDATA #REQUIRED 
                  settext CDATA #REQUIRED
                  infotext CDATA #REQUIRED 
                  default  CDATA #REQUIRED 
                  datatype (int | float | string) #REQUIRED
                  minval   CDATA #IMPLIED 
                  maxval   CDATA #IMPLIED >

<!ELEMENT switchset EMPTY >
    <!ATTLIST switchset var CDATA #REQUIRED 
                  swvar       CDATA #REQUIRED
                  settext     CDATA #REQUIRED
                  disabletext CDATA #REQUIRED
                  infotext    CDATA #REQUIRED 
                  defaultval  CDATA #REQUIRED 
                  default     (on | off) #REQUIRED 
                  datatype    (int | float | string) #REQUIRED
                  minval      CDATA #IMPLIED 
                  maxval      CDATA #IMPLIED >

<!ELEMENT file EMPTY >
   <!ATTLIST file var CDATA #REQUIRED >

<!ELEMENT direct EMPTY >
<!ELEMENT comment EMPTY >

]>

=== u-u-h/adpc/interfacer/examples/ElMamun.xml
<?xml version='1.0'?>
<!DOCTYPE interface SYSTEM "interface.dtd">

<interface name="ElMamun" interactive="on" lib="std" design="color">

<versioninfo>
(C) 2006 Fredo Schmidt
all rights reserved
</versioninfo>

<interactive>
<message>
_____             _                    _  _  _  _   _____________________
||    |   |\\  /| |_| |\\  /| | | |\\ |   _|| || || |  Elmamun 3000:
||__  |__ | \\/ | | | | \\/ | |_| | \\|   _||_||_||_|  Based on the arithm.  
||--                                                standards of 864 a.d
||      Version: 24.2.2006                          Report bugs to: 
-----                                               elmamun@acm.org

Welcome to ElMamun!
</message>
<commandline>ElMamun> </commandline>
</interactive>

<module name="seller" source="ElMamun.lhs" 
    adpc="-al seller enum -cs seller -alpp prettyprint -O -lcf -ta bto -bt so -gc cc  -cto -tadd 3 -taddc 30  | sed -f ElMamun_seller.sed  > ElMamun_seller.c "
    condition="opt->switch_seller"
    output_optimal="printf($Optimal result: #d\\nSuboptimal results in range [#d - #d]\\n$, result_score, result_score - traceback_diff, result_score);"
    output_suboptimal="printf($Score: #d -> #s \\n$, v2, result_prettyprint);"
    main_name="main_elmamun_seller"></module>

<module name="buyer" source="ElMamun.lhs" 
    adpc="-al buyer enum -cs buyer -alpp prettyprint -O -lcf -ta bto -bt so -gc cc  -cto -tadd 3 -taddc 30  | sed -f ElMamun_buyer.sed  > ElMamun_buyer.c "
    condition="opt->switch_buyer"
    output_optimal="printf($Optimal result: #d\\nSuboptimal results in range [#d - #d]\\n$, result_score, result_score - traceback_diff, result_score);"
    output_suboptimal="printf($Score: #d -> #s \\n$, v2, result_prettyprint);"
    main_name="main_elmamun_buyer"></module>


  
  <option switch="h" text="Hilf mir! Was soll ich machen?">
    <help />
    <man>

     Elmamun verwendet aktuellste Technologien. Drücke -h, und du bekommst eine Übersicht über die 
     Möglichkeiten von ElMamun. Wenn Du -H und dazu eine Option angibst, bekommst Du sogar noch etwas mehr Infos
     
    </man>

  </option>

  <option switch="H" argtext="option" text="Display detailed information on <option>">
    <longhelp />
  </option>
  
  <option switch="v" text="Show version">

   <version />
<man>ElMamun wird ständig weiterentwickelt und an die aktuellsten
   Ergebnisse der mathematischen Forschung angepasst. Drücke -v um zu
   erfahrfen wie alt deine Version ist. Falls zu alt, dann wende dich
   bitte an deine örtliche Niederlassung von ElMamun Inc. Vielleicht
   haben wir eine neue Version. Ob die besser ist, wissen wir allerdings
   nicht. </man> 
 </option>


  <option switch="s" text="Choose seller mode.">
   <mode var="switch_seller"
         settext="Switch to mode seller."
         infotext="Algebra: seller" />

   <man>
Dies ist der optimale Modus für Verkäufer. Einfach die Formel
eingeben, und ihr bekommt die optimale Klammerung. So werden Geschäfte
gemacht, hehe!

Kleiner Tipp: Mit der Option -d könnt ihr Ihr Euch auch ein paar
alternative Egebnisse anschauen. Der Verkaufspreis steht jeweils
links. Da gibt es dann vielleicht ein bisschen weniger, aber besser
irgendein Geschäft als überhaupt kein Geschäft, woll?
 
   </man>

</option>

<option switch="b" text="Choose buyer mode.">
   <mode var="switch_buyer"
         settext="Switch to mode buyer."
         infotext="Algebra: buyer" />
   <man>
ElMamun supports various modi of calculation.  If you want to buy
something, you probably don't want to pay to much. ElMamun offers the
most current calculations for these tasks. 

Our analysis showed that our algorithm in many cases gives good
results for buyers. However, a proof is still open.
   </man>

</option>



  <option switch="d" text="Set traceback diff">
     <set var="traceback_diff" datatype="int" default="5" minval="0" infotext="backtrace_value: #d"
            settext="set backtrace value to #d"/>
  </option>

  
  <option switch="f" text="Read input from file">
    <file />
  </option>
  
  <option switch="z" text="Enable colored output">
    <switch var="colored_output" />
  <code>
  if (opt->interactive && !opt->colored_output) printf(COLOR_DEFAULT);
  </code>
  </option>

</interface>

=== u-u-h/adpc/interfacer/examples/HelloWorld.xml
<?xml version='1.0'?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="HelloWorld">

<versioninfo>(c) Fredo Mueller
all rights reserved
</versioninfo>

<messageinteractive>Interactive mode. Try `#s -h` for more information.</messageinteractive>
<commandline>
Input sequence (upper or lower case); :q to quit, -h for help.
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
</commandline>

<option switch="h" text="Display this information"><help /></option>
<option switch="H" argtext="option" text="Display detailed information on <option>"><longhelp /></option>
<option switch="v" text="Show version"><version /></option>
<option switch="z" text="Enable colored output">
  <switch var="colored_output" />
<code>
if (opt->interactive && !opt->colored_output) printf(COLOR_DEFAULT);
</code>
</option>
<option switch="f" text="Read input from file"><file /></option>

<option switch="W" text="Print hello world"><direct />
<code>
printf("hello world\n");
</code>
</option>

<option switch="w" text="Window size">
<set var="window_size" datatype="int" default="5" 
   settext="Set window size to #d." infotext="Window size: #d" minval="0" />
<man>
This option sets the window size for ...

It is very nice....

</man>

</option>


</interface>

=== u-u-h/adpc/interfacer/examples/pknotsRG.xml
<?xml version='1.0'?>
<!DOCTYPE interface SYSTEM "interface.dtd">

<interface name="pknotsRG">

<versioninfo>
(C) 2006 Fredo Schmidt
all rights reserved
</versioninfo>

  <option switch="h" text="Display this information">
    <help />
  </option>
  
  <option switch="v" text="Show version">
    <version />
  </option>
  
  <option switch="f" text="Read input from file">
    <file />
  </option>
  
  <option switch="e" text="Set energy range (kcal)">
    <set var="energy" datatype="int" default="5" minval="0" />
  </option>
  
  <option switch="u" text="No dangling bases">
    <switch var="danglings" default="0" />
  </option>


   <option switch="z" text="Enable colored output">
     <switch var="colored_output" />
   <code>
   if (opt->interactive && !opt->colored_output) printf(COLOR_DEFAULT);
   </code>
   </option>

</interface>

=== u-u-h/adpc/interfacer/examples/RNAmangler.xml
<?xml version='1.0'?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="RNAmangler" version = "1.1">

<versioninfo>(c) Fredo Mueller
all rights reserved
</versioninfo>

<messageinteractive>Interactive mode. Try `#s -h` for more information.</messageinteractive>
<commandline>
Input sequence (upper or lower case); :q to quit, -h for help.
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8
</commandline>

<option switch="h" text="Display this information"><help /></option>
<option switch="H" argtext="option" text="Display detailed information on <option>"><longhelp /></option>
<option switch="v" text="Show version"><version /></option>
<option switch="a" text="Shape folding (standard)">
  <mode var="shapes" settext="Shape folding mode" default="yes" />
<man>
RNA folding based on abstract shapes. This is the standard mode of
operation when no other options are given. It calculates the shapes
and the corresponding shreps based on free energy minimization. The
energy range can be set by -e and -c. When not specified, the
energy range is set to 10% of the minimum free energy.
</man>
</option>
<option switch="s" text="Suboptimal folding mode">
  <mode var="so" />  
</option>
<option switch="p" text="Shape probabilities">
  <mode var="prob" text="Shape probability mode" />
</option>
<option switch="_" text="Additional modes"><comment /></option>
<option switch="r" text="Calculate structure probabilities">
  <switch var = "shrepprob" />
</option>
<option switch="e" text="Set energy range (kcal/mol)">
  <set var="energydiff" datatype="float" default="5" 
   settext="Set energy range to #.2f kcal//mol" infotext="xxxx Energy range #.2f kcal//mol" minval="0" />
<man>
This sets the energy range for shape folding (-a), complete
suboptimal folding (-s), probability analysis with -P, and
consensus shapes analysis (-C). value is the difference to the
minimum free energy for the sequence.
</man>
</option>
<option switch="_" text="Output:"><comment /></option>
<option switch="S" text="Set output width for structures">
  <switchset var="split_output" datatype="int" settext="Output width for structures set to #d. Type -S - to disable." 
                                               disabletext="Output splitting disabled" 
                                               infotext="xxx Output width for structures #d" minval="0" />

</option>
<option switch="m" text="Match Shape">
  <switchset var="match_string" swvar ="matcher_active"
             datatype="string" 
             settext="Match shape #s. Type -m - to disable." 
             disabletext="Shape matching disabled" 
             infotext="Match shape #s"  />
</option>

<option switch="x" text="Switch set test">
  <switchset var="switch_set_test" datatype="string" />
</option>
 

<option switch="z" text="Enable colored output">
  <switch var="colored_output" />
<code>
if (opt->interactive && !opt->colored_output) printf(COLOR_DEFAULT);
</code>
</option>

<option switch="f" text="Read input from file"><file /></option>
<option switch="w" text="Print hello world"><direct />
<code>
printf("hello world\n");
printf("hello hello hello world\n");
</code>
</option>

</interface>
